const CONFIG = {
  FOLDER_ID: 'AQUÍ EL ID DE LA CARPETA EN GOOGLE DRIVE',
  PROCESSED_FOLDER_ID: 'AQUÍ EL ID DE LA CARPETA EN GOOGLE DRIVE',
  SHEET_NAME: 'Gastos',
  CURRENCY: 'EUR',
  START_DATE: '2026-02-01'
};